license_mask = 1
mnk_capture_mouse = false
mnk_mode = true
game_data_root = "./assets"
user_data_root = "./data"
update_data_root = "./update"
user_name = "DroidSavior"
gpu_allow_invalid_fetch_constants = true
clear_memory_page_state = false
gpu_plugin = "xenos"
gpu_backend = "vulkan"

keybind_a = "J"					# Low Kick
keybind_b = "K"					# Mid Kick
keybind_x = "U"					# Low Punch
keybind_y = "I"					# Mid Punch
keybind_left_trigger = "Y"		# L+M+H Kick
keybind_right_trigger = "L"		# Heavy Kick
keybind_left_shoulder = "H"		# L+M+H Punch
keybind_right_shoulder = "O"	# Heavy Punch
keybind_back = "Escape"			# Select
keybind_start = "Return"		# Start
keybind_dpad_up = "Up"
keybind_dpad_left = "Left"
keybind_dpad_down = "Down"
keybind_dpad_right = "Right"
