#!/usr/bin/env python3
"""Offline Xenos shader -> HLSL emitter, for vertex and pixel shaders.

Reads the `.ucode` / `.header` pairs written by `extract_shaders.py`, decodes
them with `xenos_ucode.py`, and emits one HLSL source per shader. This is the
back end of the offline shader translation step: nothing here runs at game
time, and the output is meant to be compiled once by DXC/FXC into whatever the
backend consumes.

Two pieces of per-draw patching the guest's D3D does to the microcode are
replaced by host signature matching rather than reproduced:

* Vertex fetch is *lifted*. `vfetch` is not translated as an instruction; each
  shader's vertex input signature comes from the container's vertex fetch patch
  table (`xenos_ucode.vertex_fetch_table`), every entry becomes a `float4` input
  with the matching D3DDECLUSAGE semantic, and the fetch emits as a register
  move. The host input assembler does the format conversion that `sub_82267218`
  would otherwise have patched in, so the output is independent of the bound
  vertex declaration.
* Interpolators are named by *semantic key*, not by register. Both shader types
  carry an interpolator signature table (`xenos_ucode.interpolator_signature`)
  that `sub_822679A8` walks at draw time to renumber a pixel shader's input
  registers to match the bound vertex shader's. Emitting `TEXCOORD<key>` on both
  sides makes the host linker do that job instead.

Usage:
    python scripts/xenos_hlsl.py out/shaders/vs_020.ucode      # to stdout
    python scripts/xenos_hlsl.py out/shaders --all -o out/hlsl # every shader
    python scripts/xenos_hlsl.py out/shaders --all --check     # translate only

Deliberate divergences from the hardware, all of which matter only for values
a renderer should never depend on:

* `rcp`, `rsq` and `log` are emitted as the plain HLSL intrinsic, so a
  reciprocal of zero is an infinity rather than a clamped value. That is
  survivable only because `mul` reproduces the hardware's zero rule below,
  which turns the `0 * inf` that follows back into `0`. The `*c` (clamped)
  and `*f` (flushed) variants do carry their infinity clamping, since there
  the clamp is the whole point of the opcode.
* Denormal flushing on operand read is not reproduced.
* `tfetch`'s per-instruction filter and aniso fields are ignored. Every texture
  fetch in this title sets them to "take it from the fetch constant", so all
  sampler state comes from the host sampler, which is where it belongs.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import xenos_ucode as U
from xenos_ucode import bits, COMPONENTS


class EmitError(Exception):
    pass


# D3DDECLUSAGE -> HLSL input semantic. Indices match xenos_ucode.DECL_USAGES.
USAGE_SEMANTICS = {
    0: "POSITION", 1: "BLENDWEIGHT", 2: "BLENDINDICES", 3: "NORMAL",
    4: "PSIZE", 5: "TEXCOORD", 6: "TANGENT", 7: "BINORMAL",
    8: "TESSFACTOR", 9: "POSITIONT", 10: "COLOR", 11: "FOG",
    12: "DEPTH", 13: "SAMPLE",
}

# Export register numbers, from the survey of all 260 shaders in this title.
EXPORT_POSITION = 62
EXPORT_POINT_SIZE = 63
MAX_INTERPOLATOR = 15

# Two varyings of our own, carried alongside the guest's interpolators. They are
# TEXCOORD<n> like everything else so that DXC assigns them locations the same
# way under SPIR-V; the numbers are above every semantic key in the title, which
# reserved_semantics() asserts.
#
# PARAM_GEN_KEY carries the point sprite coordinate in zw. On the console this
# is PsParamGen, a register the sequencer synthesises rather than something the
# vertex shader exports (SQ_CONTEXT_MISC::param_gen_pos says which register it
# lands in, SQ_PROGRAM_CNTL::param_gen whether it is generated at all). Only the
# geometry shader below can know it, so it travels as its own varying and the
# pixel shader moves it into the register the guest reads.
#
# POINT_SIZE_KEY is the vertex shader's own e63 export, which the hardware feeds
# to the point sprite expansion. Every vertex shader declares it, exported or
# not, so one geometry shader serves all of them; a shader that does not export
# it leaves the -1 that means "use PA_SU_POINT_SIZE instead".
PARAM_GEN_KEY = 254
POINT_SIZE_KEY = 255


def reserved_semantics(layout):
    if PARAM_GEN_KEY in layout or POINT_SIZE_KEY in layout:
        raise EmitError("semantic key %d is reserved for the renderer's own "
                        "varyings" % PARAM_GEN_KEY)
    return ["    float4 out_param_gen : TEXCOORD%d;" % PARAM_GEN_KEY,
            "    float out_point_size : TEXCOORD%d;" % POINT_SIZE_KEY]

PRELUDE_HEAD = """\
// Generated by scripts/xenos_hlsl.py -- do not edit.
// Source: %(source)s

cbuffer XeFloatConsts : register(b%(cb_float)d, space%(cb_space)d) { float4 c[256]; };
cbuffer XeBoolConsts  : register(b%(cb_bool)d, space%(cb_space)d) { uint4 xe_bools[2]; uint4 xe_loops[8]; };

bool xe_bool(uint index) {
    return (xe_bools[index >> 7u][(index >> 5u) & 3u] & (1u << (index & 31u))) != 0u;
}

// Loop constant: iteration count in bits 0..7, initial aL in 8..15, and the
// signed step added to aL each iteration in 16..23.
uint xe_loop(uint index) { return xe_loops[index >> 2u][index & 3u]; }
int xe_loop_count(uint v) { return int(v & 0xFFu); }
int xe_loop_start(uint v) { return int((v >> 8u) & 0xFFu); }
int xe_loop_step(uint v) { return int(v << 8u) >> 24; }
"""

# Alpha test, which is fixed function on the console and does not exist on any
# host this targets. RB_COLORCONTROL carries the compare function and
# RB_ALPHA_REF the reference value, and both are ordinary render state that the
# guest changes between draws, so baking them into the shader would mean a
# variant per (shader, function) pair. They arrive as constants instead and the
# branch is uniform, which costs nothing a real branch would not.
#
# The disabled case is spelled as ALWAYS by the runtime that fills this, so a
# shader with the alpha test off takes the same path with no discard.
# Render state that is fixed function on the console and has no host equivalent,
# so it reaches the shaders as constants. One buffer rather than two because the
# geometry shader and the pixel shader both want a slice of it and a root
# descriptor is per pipeline layout, not per stage.
#
# param_gen_pos is a *register* index, not a semantic key: the pixel shader below
# switches on it to move PsParamGen into the register the guest microcode reads.
# See PARAM_GEN_KEY.
DRAW_STATE_CB = """\
cbuffer XeDrawState : register(b%(cb_alpha)d, space%(cb_space)d) {
    uint xe_alpha_func;  // xenos::CompareFunction
    float xe_alpha_ref;
    uint xe_param_gen_pos;
    uint xe_param_gen_enable;
    // PA_SU_POINT_SIZE as a diameter in host pixels, and the reciprocal of the
    // viewport extent that turns it into a clip space radius. See the geometry
    // shader for why the y half can arrive negative.
    float2 xe_point_constant_diameter;
    float2 xe_point_screen_to_ndc;
    // PA_SU_POINT_MINMAX, the range rasterisation clamps an e63 diameter to,
    // and whether the bound vertex shader exports one at all.
    float2 xe_point_size_minmax;
    uint xe_point_size_from_vertex;
    uint xe_draw_state_pad;
    // World clip space compression. The guest projects at 16:9 while the world
    // image covers the whole window, so squeezing clip space by the fraction of
    // the window that 16:9 frame occupies turns the margins into real field of
    // view instead of a stretch. (1, 1) for the UI layer and for any pass whose
    // position is already in clip space.
    float2 xe_clip_scale;
};
"""

PRELUDE_ALPHA_TEST = """\
%(draw_state)s

void xe_alpha_test(float a) {
    bool pass;
    switch (xe_alpha_func) {
        case 0u:  pass = false;             break;  // never
        case 1u:  pass = a <  xe_alpha_ref; break;  // less
        case 2u:  pass = a == xe_alpha_ref; break;  // equal
        case 3u:  pass = a <= xe_alpha_ref; break;  // lessequal
        case 4u:  pass = a >  xe_alpha_ref; break;  // greater
        case 5u:  pass = a != xe_alpha_ref; break;  // notequal
        case 6u:  pass = a >= xe_alpha_ref; break;  // greaterequal
        default:  pass = true;              break;  // always
    }
    if (!pass) {
        discard;
    }
}
"""

PRELUDE_ALU = """\
// Xenos multiplies are not IEEE. If either operand is zero (or denormal, which
// the hardware flushes to zero on read) the result is +0 even when the other
// operand is an infinity or a NaN, where IEEE would give NaN. Reproducing this
// is not pedantry: the guest parks unused light slots at constants that make a
// divisor zero, so the reciprocal is an infinity and the product after it is
// finite only because the hardware forces it to zero. A plain `*` leaks a NaN
// into the colour, and a NaN written to a UNORM target reads back as black.
//
// The test is min(|a|, |b|) == 0 so that a NaN operand does not satisfy it:
// NaN compares false, which leaves the IEEE product alone, which is also what
// the hardware does.
float4 xe_mul(float4 a, float4 b) {
    float4 p = a * b;
    float4 z = min(abs(a), abs(b));
    return float4(z.x == 0.0f ? 0.0f : p.x, z.y == 0.0f ? 0.0f : p.y,
                  z.z == 0.0f ? 0.0f : p.z, z.w == 0.0f ? 0.0f : p.w);
}
float xe_muls(float a, float b) {
    return min(abs(a), abs(b)) == 0.0f ? 0.0f : a * b;
}

// Xenos writes the scalar result of a dot product to every masked component.
// The products go through the rule above and are summed in order, because a
// zeroed product and a NaN one do not sum the same way.
float4 xe_dp4(float4 a, float4 b) {
    float4 p = xe_mul(a, b);
    return (((p.x + p.y) + p.z) + p.w).xxxx;
}
float4 xe_dp3(float4 a, float4 b) {
    float4 p = xe_mul(a, b);
    return ((p.x + p.y) + p.z).xxxx;
}
float4 xe_dp2add(float4 a, float4 b, float4 c) {
    float4 p = xe_mul(a, b);
    return ((p.x + p.y) + c.x).xxxx;
}
float4 xe_max4(float4 a) {
    return max(max(a.x, a.y), max(a.z, a.w)).xxxx;
}

// cnd* select per component against the first operand.
float4 xe_cndeq(float4 a, float4 b, float4 c) {
    return float4(a.x == 0.0f ? b.x : c.x, a.y == 0.0f ? b.y : c.y,
                  a.z == 0.0f ? b.z : c.z, a.w == 0.0f ? b.w : c.w);
}
float4 xe_cndge(float4 a, float4 b, float4 c) {
    return float4(a.x >= 0.0f ? b.x : c.x, a.y >= 0.0f ? b.y : c.y,
                  a.z >= 0.0f ? b.z : c.z, a.w >= 0.0f ? b.w : c.w);
}
float4 xe_cndgt(float4 a, float4 b, float4 c) {
    return float4(a.x > 0.0f ? b.x : c.x, a.y > 0.0f ? b.y : c.y,
                  a.z > 0.0f ? b.z : c.z, a.w > 0.0f ? b.w : c.w);
}

// D3D9 dst: { 1, a.y * b.y, a.z, b.w }.
float4 xe_dst(float4 a, float4 b) {
    return float4(1.0f, a.y * b.y, a.z, b.w);
}

// Relative constant reads are clamped into the bank rather than left out of
// bounds, which is undefined for a host constant buffer.
uint xe_ci(int index) { return (uint)clamp(index, 0, 255); }

// maxas writes the address register as floor(clamp(src, -256, 255) + 0.5).
int xe_maxas_addr(float v) { return int(floor(clamp(v, -256.0f, 255.0f) + 0.5f)); }
int xe_maxasf_addr(float v) { return int(floor(clamp(v, -256.0f, 255.0f))); }

// Clamped / flushed reciprocal variants, where the clamp is the opcode.
float xe_rcpc(float v) { return clamp(1.0f / v, -3.402823466e+38f, 3.402823466e+38f); }
float xe_rcpf(float v) { float r = 1.0f / v; return isinf(r) ? (r < 0.0f ? -0.0f : 0.0f) : r; }
float xe_rsqc(float v) { return clamp(rsqrt(v), -3.402823466e+38f, 3.402823466e+38f); }
float xe_rsqf(float v) { float r = rsqrt(v); return isinf(r) ? (r < 0.0f ? -0.0f : 0.0f) : r; }
float xe_logc(float v) { float r = log2(v); return isinf(r) && r < 0.0f ? -3.402823466e+38f : r; }
"""

# `cube` takes one operand already swizzled to .z_xy and returns the cube map
# coordinate as (T, S, 2 * major axis, face id). Transcribed from xenia's
# AluVectorOpcode::kCube lowering in dxbc_shader_translator_alu.cc.
PRELUDE_CUBE = """\
float4 xe_cube(float4 s) {
    float x = s.z, y = s.w, z = s.x;
    float tc, sc, ma, id;
    if (abs(z) >= abs(x) && abs(z) >= abs(y)) {
        bool n = z < 0.0f;
        tc = -y; sc = n ? -x : x; ma = 2.0f * z; id = n ? 5.0f : 4.0f;
    } else if (abs(y) >= abs(x)) {
        bool n = y < 0.0f;
        tc = n ? -z : z; sc = x; ma = 2.0f * y; id = n ? 3.0f : 2.0f;
    } else {
        bool n = x < 0.0f;
        tc = -y; sc = n ? z : -z; ma = 2.0f * x; id = n ? 1.0f : 0.0f;
    }
    return float4(tc, sc, ma, id);
}
"""


def _vector_emitters():
    def binary(op):
        return lambda s: "(%s %s %s)" % (s[0], op, s[1])

    def compare(op):
        return lambda s: "float4(%s %s %s)" % (s[0], op, s[1])

    def call(name, count):
        return lambda s: "%s(%s)" % (name, ", ".join(s[:count]))

    return {
        "add": binary("+"), "mul": call("xe_mul", 2),
        "max": call("max", 2), "min": call("min", 2),
        "seq": compare("=="), "sgt": compare(">"),
        "sge": compare(">="), "sne": compare("!="),
        "frc": call("frac", 1), "trunc": call("trunc", 1),
        "floor": call("floor", 1),
        "mad": lambda s: "(xe_mul(%s, %s) + %s)" % (s[0], s[1], s[2]),
        "cndeq": call("xe_cndeq", 3), "cndge": call("xe_cndge", 3),
        "cndgt": call("xe_cndgt", 3),
        "dp4": call("xe_dp4", 2), "dp3": call("xe_dp3", 2),
        "dp2add": call("xe_dp2add", 3), "max4": call("xe_max4", 1),
        "dst": call("xe_dst", 2), "cube": call("xe_cube", 1),
        "maxa": call("max", 2),  # address register write handled separately
    }


VECTOR_EMITTERS = _vector_emitters()

# Vector ops needing the cube prelude.
VECTOR_HELPER_PRELUDES = {"cube": PRELUDE_CUBE}

# Scalar opcode -> expression over `a` (first component), `b` (second, only for
# the two-component and constant forms) and `ps` (the previous scalar result).
SCALAR_EMITTERS = {
    "adds": "({a} + {b})",
    "adds_prev": "({a} + ps)",
    "muls": "xe_muls({a}, {b})",
    "muls_prev": "xe_muls({a}, ps)",
    "muls_prev2": "xe_muls({a}, ps)",
    "maxs": "max({a}, {b})",
    "mins": "min({a}, {b})",
    "seqs": "float({a} == 0.0f)",
    "sgts": "float({a} > 0.0f)",
    "sges": "float({a} >= 0.0f)",
    "snes": "float({a} != 0.0f)",
    "frcs": "frac({a})",
    "truncs": "trunc({a})",
    "floors": "floor({a})",
    "exp": "exp2({a})",
    "log": "log2({a})",
    "logc": "xe_logc({a})",
    "rcp": "(1.0f / {a})",
    "rcpc": "xe_rcpc({a})",
    "rcpf": "xe_rcpf({a})",
    "rsq": "rsqrt({a})",
    "rsqc": "xe_rsqc({a})",
    "rsqf": "xe_rsqf({a})",
    "sqrt": "sqrt({a})",
    "sin": "sin({a})",
    "cos": "cos({a})",
    "subs": "({a} - {b})",
    "subs_prev": "({a} - ps)",
    "maxas": "max({a}, {b})",
    "maxasf": "max({a}, {b})",
    "mulsc": "xe_muls({a}, {b})",
    "addsc": "({a} + {b})",
    "subsc": "({a} - {b})",
    "retain_prev": "ps",
    # setp_* also write the predicate; see SCALAR_PREDICATE_WRITERS. The value
    # written to ps is 0 when the predicate is set and 1 otherwise.
    "setp_eq": "(p0 ? 0.0f : 1.0f)",
    "setp_ne": "(p0 ? 0.0f : 1.0f)",
}

# Scalar ops that also write the address register, and the helper that does it.
SCALAR_ADDRESS_WRITERS = {"maxas": "xe_maxas_addr", "maxasf": "xe_maxasf_addr"}

# Scalar ops that write the predicate register, and the test they apply to
# their first operand. The predicate write happens before ps is computed.
SCALAR_PREDICATE_WRITERS = {"setp_eq": "==", "setp_ne": "!="}

# Scalar ops reading two components of their single operand (ucode.cc's
# `single_operand_is_two_component`).
SCALAR_TWO_COMPONENT = {
    "adds", "muls", "muls_prev2", "maxs", "mins", "maxas", "maxasf", "subs",
}


class Shader:
    """Common decoding, operand construction, ALU and control flow emission."""

    def __init__(self, name, ucode, header):
        self.name = name
        self.decoded = U.decode(ucode)
        self.dwords = U.read_dwords(ucode[self.decoded["prefix"]:])
        # The literal pool the compiler placed in constants 252..255. Not part
        # of the emitted code: the host has to upload it alongside the guest's
        # own constants, because nothing in the guest ever writes it.
        self.literals = U.literal_constants(ucode, self.decoded["prefix"])
        self.header = header
        self.interpolators = U.interpolator_signature(header) if header else []
        # The interpolator layout both stages declare.
        #
        # D3D12 matches a pixel shader's input signature against the vertex
        # shader's output signature by *register*, not only by semantic name, so
        # two shaders carrying different subsets of the title's semantic keys do
        # not link even though every name matches: HLSL assigns registers by
        # declaration order, so the same key lands in a different register on
        # each side. The driver says so in as many words -- "Semantic 'TEXCOORD'
        # is defined for mismatched hardware registers between the output stage
        # and input stage".
        #
        # One layout for the whole title fixes it: every shader declares every
        # key, in ascending order, so a key's register is the same everywhere. A
        # vertex shader leaves the keys it does not export at zero and a pixel
        # shader ignores the ones it does not read. There are only twelve keys
        # in this title, well inside the interpolator budget.
        #
        # None means "this shader's own keys", which is all a standalone
        # translation of a single shader can know.
        self.interpolator_layout = None
        self.unsupported = []
        self._scan()

    # -- analysis ------------------------------------------------------------

    def _scan(self):
        self.max_temp = 0
        self.exports = set()
        self.textures = {}
        self.helpers = set()
        self.uses_address_register = False
        self.uses_loop_register = False
        self.uses_predicate = False

        for cf in self.decoded["control_flow"]:
            self._scan_control_flow(cf)

        for address, instr in sorted(self.decoded["instructions"].items()):
            if instr["type"] == "fetch":
                if instr["predicated"]:
                    self.uses_predicate = True
                self._scan_fetch(address, instr)
                continue
            if instr["predicated"]:
                self.uses_predicate = True
            if instr["vector_dest_rel"]:
                self.unsupported.append("relative destination at %d" % address)
            if instr["vector_name"] not in VECTOR_EMITTERS:
                self.unsupported.append(
                    "vector op '%s' at %d" % (instr["vector_name"], address))
            elif instr["vector_name"] in VECTOR_HELPER_PRELUDES:
                self.helpers.add(instr["vector_name"])
            if instr["scalar_name"] not in SCALAR_EMITTERS:
                self.unsupported.append(
                    "scalar op '%s' at %d" % (instr["scalar_name"], address))
            if instr["scalar_name"] in SCALAR_ADDRESS_WRITERS:
                self.uses_address_register = True
            if instr["scalar_name"] in SCALAR_PREDICATE_WRITERS:
                self.uses_predicate = True

            if U.SCALAR_OPS[instr["scalar_opcode"]][1] == 2:
                # mulsc/addsc/subsc address a temp the source fields do not
                # name; see `_scalar_operand`.
                self.max_temp = max(self.max_temp, self._constant_op_temp(instr,
                                                                          address))
            w1 = self._raw(address, 1)
            for index, source in enumerate(instr["sources"]):
                if source["is_temp"]:
                    self.max_temp = max(self.max_temp, source["reg"] & 0x3F)
                elif self._const_is_addressed(instr, index + 1, w1):
                    # Bit 29 picks the address register over the loop counter.
                    if bits(w1, 29, 1):
                        self.uses_address_register = True
                    else:
                        self.uses_loop_register = True
            if instr["export"]:
                self.exports.add(instr["vector_dest"])
            else:
                self.max_temp = max(self.max_temp, instr["vector_dest"])
                if instr["scalar_write_mask"]:
                    self.max_temp = max(self.max_temp, instr["scalar_dest"])

        # Interpolators arrive in registers whether or not the shader's ALU
        # instructions ever name them.
        for entry in self.interpolators:
            self.max_temp = max(self.max_temp, entry["register"])

        self._scan_exports()

    def _constant_op_temp(self, instr, address):
        swizzle = instr["sources"][2]["swizzle"]
        return ((instr["scalar_opcode"] & 1)
                | (bits(self._raw(address, 2), 29, 1) << 1)
                | (swizzle & 0x3C))

    def _scan_control_flow(self, cf):
        if cf.opcode in (9, 10, 15):
            self.unsupported.append("control flow op '%s'" % cf.name)
        elif cf.opcode in (7, 8):
            self.uses_loop_register = True
            if cf.opcode == 7 and cf.is_repeat:
                self.unsupported.append("repeat loop")
            if cf.opcode == 8 and cf.is_predicated_break:
                self.unsupported.append("predicated loop break")
        elif cf.opcode == 11 and cf.is_predicated:
            self.uses_predicate = True
        elif cf.opcode in U.CF_COND_PRED:
            self.uses_predicate = True

    def _scan_fetch(self, address, instr):
        raise NotImplementedError

    def _scan_exports(self):
        raise NotImplementedError

    # -- operand construction ------------------------------------------------

    def _raw(self, address, word):
        return self.dwords[address * 3 + word]

    def _source_register(self, instr, address, index):
        """The register an ALU source names, without swizzle or modifiers."""
        source = instr["sources"][index - 1]
        if source["is_temp"]:
            return "r%d" % (source["reg"] & 0x3F)
        w1 = self._raw(address, 1)
        if self._const_is_addressed(instr, index, w1):
            base = "a0" if bits(w1, 29, 1) else "aL"
            return "c[xe_ci(%s + %d)]" % (base, source["reg"])
        return "c[%d]" % source["reg"]

    def _source_modifiers(self, instr, address, index, text):
        """Wrap a source expression in its absolute-value and negate modifiers.

        Temps carry absolute value in bit 0x80 of their own register field;
        constants carry it in the instruction-wide `abs_constants`. Absolute
        value binds tighter than the negate, so both together read -|x|.
        """
        source = instr["sources"][index - 1]
        absolute = source["absolute"] or (
            not source["is_temp"] and bits(self._raw(address, 0), 7, 1))
        if absolute:
            text = "abs(%s)" % text
        if source["negate"]:
            text = "-%s" % text
        return text

    def _source(self, instr, address, index, component_count=4):
        """Build the HLSL expression for ALU source operand `index` (1..3)."""
        swizzle = instr["sources"][index - 1]["swizzle"]
        text = self._source_register(instr, address, index)
        if component_count == 1:
            text += "." + COMPONENTS[U.swizzled_component(swizzle, 3)]
        else:
            text += "." + "".join(
                COMPONENTS[U.swizzled_component(swizzle, j)]
                for j in range(component_count))
        return self._source_modifiers(instr, address, index, text)

    @staticmethod
    def _const_is_addressed(instr, index, w1):
        """ucode.h `src_const_is_addressed`: which rel_abs bit applies."""
        const_1_rel_abs = bits(w1, 30, 1)
        const_0_rel_abs = bits(w1, 31, 1)
        temp = [s["is_temp"] for s in instr["sources"]]
        if index == 1:
            return bool(const_0_rel_abs)
        if index == 2:
            return bool(const_0_rel_abs if temp[0] else const_1_rel_abs)
        return bool(const_0_rel_abs if temp[0] and temp[1] else const_1_rel_abs)

    def _scalar_operand(self, instr, address, which):
        """Component `which` (0 or 1) of the scalar half's operand."""
        source = instr["sources"][2]
        swizzle = source["swizzle"]
        scalar_opcode = instr["scalar_opcode"]
        if U.SCALAR_OPS[scalar_opcode][1] == 2:
            # mulsc/addsc/subsc: a constant in src3 and a temp whose index is
            # assembled from the opcode's low bit, src3_sel and the swizzle.
            if which == 0:
                text = "c[%d].%s" % (source["reg"],
                                     COMPONENTS[U.swizzled_component(swizzle, 3)])
            else:
                text = "r%d.%s" % (self._constant_op_temp(instr, address),
                                   COMPONENTS[U.swizzled_component(swizzle, 0)])
            if source["negate"]:
                text = "-%s" % text
            return text
        # The scalar half reads swizzle slots 3 and 0, in that order, not 0 and
        # 1: xenia's shader_interpreter takes `(3 + i) & 3`. Reading slot 0
        # twice made every two-component op fold to a constant (`subs` to 0,
        # which then reached a `rcp` and produced an infinity).
        component = U.swizzled_component(swizzle, 3 if which == 0 else 0)
        text = "%s.%s" % (self._source_register(instr, address, 3),
                          COMPONENTS[component])
        return self._source_modifiers(instr, address, 3, text)

    def _scalar_expression(self, instr, address, scalar_name):
        template = SCALAR_EMITTERS[scalar_name]
        if "{" not in template:
            return template
        two_component = (scalar_name in SCALAR_TWO_COMPONENT
                         or U.SCALAR_OPS[instr["scalar_opcode"]][1] == 2)
        a = self._scalar_operand(instr, address, 0)
        b = self._scalar_operand(instr, address, 1) if two_component else None
        return template.format(a=a, b=b)

    # -- instruction emission ------------------------------------------------

    @staticmethod
    def _predicate_test(instr):
        """The `(p0)` / `(!p0)` guard an instruction carries, if any."""
        if not instr["predicated"]:
            return None
        return "p0" if instr["pred_condition"] else "!p0"

    def _emit_block(self, out, indent, instr, lines):
        """Emit one instruction's lines, wrapped in its predicate guard."""
        test = self._predicate_test(instr)
        head = "if (%s) " % test if test else ""
        out.append("%s%s{  // %s" % (indent, head, instr["text"]))
        for line in lines:
            out.append("%s    %s" % (indent, line))
        out.append("%s}" % indent)

    def _emit_alu(self, instr, out, indent):
        address = instr["address"]
        w0 = self._raw(address, 0)
        vector_clamp = bits(w0, 24, 1)
        scalar_clamp = bits(w0, 25, 1)

        vector_name = instr["vector_name"]
        scalar_name = instr["scalar_name"]
        operand_count = max(U.VECTOR_OPS[instr["vector_opcode"]][1], 1)
        if vector_name == "cube":
            operand_count = 1  # one operand, pre swizzled to .z_xy

        export = instr["export"]
        vector_mask = instr["vector_write_mask"]
        scalar_mask = instr["scalar_write_mask"]
        writes_vector = bool(vector_mask) or export
        # `retain_prev` (50) with an empty mask is the encoding for "no scalar
        # operation", which is how a vector-only instruction is written.
        writes_scalar = bool(scalar_mask) or (
            instr["scalar_opcode"] != 50
            and U.SCALAR_OPS[instr["scalar_opcode"]][1])

        lines = []
        if writes_vector:
            sources = [self._source(instr, address, i + 1)
                       for i in range(operand_count)]
            expression = VECTOR_EMITTERS[vector_name](sources)
            if vector_clamp:
                expression = "saturate(%s)" % expression
            lines.append("float4 vr = %s;" % expression)

        if writes_scalar:
            test = SCALAR_PREDICATE_WRITERS.get(scalar_name)
            if test:
                lines.append("p0 = (%s %s 0.0f);"
                             % (self._scalar_operand(instr, address, 0), test))
            expression = self._scalar_expression(instr, address, scalar_name)
            if scalar_clamp:
                expression = "saturate(%s)" % expression
            lines.append("ps = %s;" % expression)
            writer = SCALAR_ADDRESS_WRITERS.get(scalar_name)
            if writer:
                lines.append("a0 = %s(%s);"
                             % (writer, self._scalar_operand(instr, address, 0)))

        # Destination writes come last so both halves read pre-write registers.
        if export:
            lines.extend(self._export_writes(instr, writes_vector, writes_scalar))
        else:
            if vector_mask:
                mask = U.write_mask_str(vector_mask)
                lines.append("r%d.%s = vr.%s;"
                             % (instr["vector_dest"], mask, mask))
            if scalar_mask:
                lines.append("r%d.%s = ps;"
                             % (instr["scalar_dest"],
                                U.write_mask_str(scalar_mask)))

        if lines:
            self._emit_block(out, indent, instr, lines)

    def _export_writes(self, instr, writes_vector, writes_scalar):
        """Exports: the two masks together also encode constants 0 and 1."""
        target = self._export_target(instr["vector_dest"])
        vector_mask = instr["vector_write_mask"]
        scalar_mask = instr["scalar_write_mask"]
        lines = []
        for i in range(4):
            vector = (vector_mask >> i) & 1
            scalar = (scalar_mask >> i) & 1
            component = COMPONENTS[i]
            if vector and scalar:
                value = "1.0f"
            elif vector:
                value = "vr.%s" % component if writes_vector else None
            elif scalar:
                value = "ps" if writes_scalar else None
            elif instr["scalar_dest_rel"]:
                value = "0.0f"
            else:
                continue
            if value is None:
                continue
            lines.append("%s.%s = %s;" % (target, component, value))
        return lines

    def _export_target(self, register):
        raise NotImplementedError

    def _emit_fetch(self, instr, out, indent):
        raise NotImplementedError

    def _fetch_destination(self, instr, source_expression):
        """Apply a fetch's destination swizzle, where 4 and 5 are 0 and 1."""
        parts = []
        for i in range(4):
            selector = bits(instr["dst_swizzle"], i * 3, 3)
            if selector >= 6:  # keep the old value, or left unwritten
                continue
            if selector == 4:
                value = "0.0f"
            elif selector == 5:
                value = "1.0f"
            else:
                value = "%s.%s" % (source_expression, COMPONENTS[selector])
            parts.append((COMPONENTS[i], value))
        if not parts:
            return None
        mask = "".join(component for component, _ in parts)
        values = ", ".join(value for _, value in parts)
        suffix = "float%d(%s)" % (len(parts), values) if len(parts) > 1 else values
        return "r%d.%s = %s;" % (instr["dst_reg"], mask, suffix)

    # -- control flow --------------------------------------------------------

    def _emit_body(self, out, indent):
        """Structure the control flow into if / else / loop and emit it.

        Every jump in all 260 shaders is forward and the guarded regions nest
        properly, so a jump at block `i` targeting `T` guards blocks
        `i+1 .. T-1`, and an unconditional jump as that region's last block is
        the `else` terminator of the same conditional. Anything else raises
        rather than emitting something plausible.
        """
        self._structure(out, indent, 0, len(self.decoded["control_flow"]))

    def _structure(self, out, indent, lo, hi):
        cfs = self.decoded["control_flow"]
        index = lo
        while index < hi:
            cf = cfs[index]
            if cf.opcode == 7:  # loop
                index = self._structure_loop(out, indent, index, hi) + 1
                continue
            if cf.opcode == 8:
                raise EmitError("stray endloop at %d in %s" % (index, self.name))
            if cf.opcode == 11:  # jmp
                index = self._structure_jump(out, indent, index, hi)
                continue
            self._emit_exec(out, indent, cf)
            index += 1

    def _structure_loop(self, out, indent, index, hi):
        cf = self.decoded["control_flow"][index]
        end = self._matching_endloop(index, hi)
        out.append("%s{  // %s" % (indent, cf))
        out.append("%s    uint xe_lc = xe_loop(%du);" % (indent, cf.loop_id))
        out.append("%s    int xe_count = xe_loop_count(xe_lc);" % indent)
        out.append("%s    int xe_step = xe_loop_step(xe_lc);" % indent)
        out.append("%s    aL = xe_loop_start(xe_lc);" % indent)
        out.append("%s    for (int xe_i = 0; xe_i < xe_count; ++xe_i) {" % indent)
        self._structure(out, indent + "        ", index + 1, end)
        out.append("%s        aL += xe_step;" % indent)
        out.append("%s    }" % indent)
        out.append("%s}" % indent)
        return end

    def _matching_endloop(self, index, hi):
        cfs = self.decoded["control_flow"]
        depth = 0
        for probe in range(index + 1, hi):
            if cfs[probe].opcode == 7:
                depth += 1
            elif cfs[probe].opcode == 8:
                if depth == 0:
                    return probe
                depth -= 1
        raise EmitError("unmatched loop at %d in %s" % (index, self.name))

    def _structure_jump(self, out, indent, index, hi):
        cfs = self.decoded["control_flow"]
        cf = cfs[index]
        target = cf.jump_address
        if target <= index:
            raise EmitError("backward jump at %d in %s" % (index, self.name))
        if target > hi:
            raise EmitError("jump out of its region at %d in %s"
                            % (index, self.name))

        # An unconditional jump as the last block of the guarded region is the
        # `else` terminator of this conditional, not a region of its own.
        body_end, else_end = target, None
        last = cfs[target - 1] if target - 1 > index else None
        if last is not None and last.opcode == 11 and last.is_unconditional \
                and last.jump_address > target:
            if last.jump_address > hi:
                raise EmitError("else target out of its region at %d in %s"
                                % (target - 1, self.name))
            body_end, else_end = target - 1, last.jump_address

        if cf.is_unconditional:
            raise EmitError("unconditional jump at %d in %s is not an else "
                            "terminator" % (index, self.name))

        # The jump is taken when its condition holds, so the guarded region
        # runs on the *inverse* of the encoded condition.
        if cf.is_predicated:
            test = "!p0" if cf.condition else "p0"
        else:
            test = "%sxe_bool(%du)" % ("!" if cf.condition else "",
                                       cf.bool_address)
        out.append("%sif (%s) {  // %s" % (indent, test, cf))
        self._structure(out, indent + "    ", index + 1, body_end)
        if else_end is None:
            out.append("%s}" % indent)
            return target
        out.append("%s} else {" % indent)
        self._structure(out, indent + "    ", body_end + 1, else_end)
        out.append("%s}" % indent)
        return else_end

    def _emit_exec(self, out, indent, cf):
        if cf.opcode in (0, 12):  # nop, alloc
            return
        if not cf.is_exec:
            raise EmitError("unhandled control flow '%s' in %s"
                            % (cf.name, self.name))

        # A conditional exec tests a uniform bool constant; a predicated exec
        # tests the per-pixel predicate. The `_pc` forms additionally reset the
        # hardware predicate, which nothing emitted here depends on.
        body_indent = indent
        if cf.opcode in U.CF_COND_BOOL:
            out.append("%sif (%sxe_bool(%du)) {  // %s"
                       % (indent, "" if cf.condition else "!",
                          cf.bool_address, cf))
            body_indent += "    "
        elif cf.opcode in U.CF_COND_PRED:
            out.append("%sif (%sp0) {  // %s"
                       % (indent, "" if cf.condition else "!", cf))
            body_indent += "    "

        for slot in range(cf.count):
            instr = self.decoded["instructions"][cf.address + slot]
            if instr["type"] == "fetch":
                self._emit_fetch(instr, out, body_indent)
            else:
                self._emit_alu(instr, out, body_indent)

        if body_indent != indent:
            out.append("%s}" % indent)

    # -- whole shader --------------------------------------------------------

    # Constant buffer registers, deliberately disjoint between the two shader
    # types. The guest has two independent float banks, device+1792 for vertex
    # and device+5888 for pixel, but a host root signature binds one buffer per
    # register and makes it visible to every stage; emitting b0 in both would
    # make the pixel shader read the vertex bank. See the pipeline layout in
    # src/native_renderer_pipeline.cpp, which binds these four in this order.
    CB_FLOAT = 0
    CB_BOOL = 1

    # All five constant buffers live in register space 2, which is descriptor
    # set 2 under Vulkan. They cannot share space 0 with the textures: DXC maps
    # a register number straight onto a SPIR-V binding number within its space,
    # so b0..b4 in space 0 would collide with t0..t4, and a descriptor set
    # layout cannot hold two descriptor types at one binding. D3D12 has no such
    # collision, since a root CBV and a descriptor table are separate root
    # parameters, but keeping one space for both backends keeps the generated
    # HLSL and the pipeline layout in src/native_renderer_pipeline.cpp reading
    # the same way.
    CB_SPACE = 2

    def _prelude(self, source_name):
        out = [PRELUDE_HEAD % {"source": source_name,
                               "cb_float": self.CB_FLOAT,
                               "cb_bool": self.CB_BOOL,
                               "cb_space": self.CB_SPACE},
               PRELUDE_ALU]
        for helper in sorted(self.helpers):
            out.append(VECTOR_HELPER_PRELUDES[helper])
        return out

    def _declare_registers(self, out):
        for index in range(self.max_temp + 1):
            out.append("    float4 r%d = 0.0f.xxxx;" % index)
        out.append("    float ps = 0.0f;")
        if self.uses_predicate:
            out.append("    bool p0 = false;")
        if self.uses_address_register:
            out.append("    int a0 = 0;")
        if self.uses_loop_register:
            out.append("    int aL = 0;")

    def layout_keys(self):
        if self.interpolator_layout is not None:
            return list(self.interpolator_layout)
        return sorted(e["key"] for e in self.interpolators)

    def interpolator_name(self, register):
        for entry in self.interpolators:
            if entry["register"] == register:
                return "p%d" % entry["key"]
        raise EmitError("interpolator register %d is not in %s's signature"
                        % (register, self.name))


class VertexShader(Shader):
    CB_FLOAT = 0
    CB_BOOL = 1

    def __init__(self, name, ucode, header):
        self.inputs = U.vertex_fetch_table(header) if header else []
        self.by_instruction = {e["instruction"]: e for e in self.inputs}
        Shader.__init__(self, name, ucode, header)
        self._scan_position_source()

    # Dot products are what a projection is made of, so a position that never
    # passes through one against a vertex constant is already in clip space.
    DOT_OPS = ("dp4", "dp3", "dp2add")

    def _scan_position_source(self):
        """Decide whether the position export is a projection.

        Only a projected position may have clip space compressed by
        xe_clip_scale: a fullscreen pass writes its quad at x in [-1, 1], and
        squeezing that leaves unwritten bars down the sides of the image, which
        read as unblurred margins rather than as an obvious black bar.

        Taint starts at a dot product with a constant operand and propagates
        through every later use, so a quad that merely offsets itself by a
        constant stays untainted. Control flow is ignored, hence the fixpoint.
        """
        self.projects_position = False
        alu = [instr for instr in self.decoded["instructions"].values()
               if instr["type"] != "fetch"]
        tainted = set()
        while True:
            changed = False
            for instr in alu:
                count = max(U.VECTOR_OPS[instr["vector_opcode"]][1], 1)
                sources = instr["sources"][:count]
                hot = any(s["is_temp"] and s["reg"] in tainted for s in sources)
                if not hot and instr["vector_name"] in self.DOT_OPS:
                    hot = any(not s["is_temp"] for s in sources)
                if hot:
                    if instr["export"]:
                        if (instr["vector_dest"] == EXPORT_POSITION
                                and not self.projects_position):
                            self.projects_position = True
                            changed = True
                    elif instr["vector_dest"] not in tainted:
                        tainted.add(instr["vector_dest"])
                        changed = True
                # The scalar half reads src3 and writes its own register.
                scalar = instr["sources"][2]
                if (scalar["is_temp"] and scalar["reg"] in tainted
                        and not instr["export"]
                        and instr["scalar_dest"] not in tainted):
                    tainted.add(instr["scalar_dest"])
                    changed = True
            if not changed:
                break

    def _scan_fetch(self, address, instr):
        if instr["opcode"] != 0:
            self.unsupported.append(
                "non-vertex fetch '%s' at %d" % (instr["name"], address))
        elif address not in self.by_instruction:
            self.unsupported.append(
                "vfetch at %d has no vertex fetch table entry" % address)
        self.max_temp = max(self.max_temp, instr["dst_reg"], instr["src_reg"])

    def _scan_exports(self):
        if EXPORT_POSITION not in self.exports:
            self.unsupported.append("no position export")
        for export in self.exports:
            if export > MAX_INTERPOLATOR and export not in (
                    EXPORT_POSITION, EXPORT_POINT_SIZE):
                self.unsupported.append("unknown export register e%d" % export)

    def _export_target(self, register):
        if register == EXPORT_POSITION:
            return "out_position"
        if register == EXPORT_POINT_SIZE:
            return "out_point_size"
        return "out_" + self.interpolator_name(register)

    def _emit_fetch(self, instr, out, indent):
        entry = self.by_instruction[instr["address"]]
        source = "in_%s%d" % (entry["usage_name"].lower(), entry["usage_index"])
        line = self._fetch_destination(instr, source)
        if line:
            self._emit_block(out, indent, instr, [line])

    def emit(self, source_name):
        registers = sorted(e for e in self.exports if e <= MAX_INTERPOLATOR)
        names = [self.interpolator_name(r) for r in registers]
        out = self._prelude(source_name)
        if self.projects_position:
            out.append(DRAW_STATE_CB % {"cb_alpha": PixelShader.CB_ALPHA,
                                        "cb_space": self.CB_SPACE})

        out.append("struct VSInput {")
        for entry in self.inputs:
            out.append("    float4 in_%s%d : %s%d;"
                       % (entry["usage_name"].lower(), entry["usage_index"],
                          USAGE_SEMANTICS[entry["usage"]], entry["usage_index"]))
        out.append("};\n")

        out.append("struct VSOutput {")
        out.append("    float4 out_position : SV_Position;")
        for key in self.layout_keys():
            out.append("    float4 out_p%d : TEXCOORD%d;" % (key, key))
        out.extend(reserved_semantics(self.layout_keys()))
        out.append("};\n")

        out.append("VSOutput main(VSInput input) {")
        out.append("    VSOutput output = (VSOutput)0;")
        self._declare_registers(out)
        out.append("")
        for entry in self.inputs:
            name = "in_%s%d" % (entry["usage_name"].lower(), entry["usage_index"])
            out.append("    float4 %s = input.%s;" % (name, name))
        out.append("    float4 out_position = 0.0f.xxxx;")
        for name in names:
            out.append("    float4 out_%s = 0.0f.xxxx;" % name)
        # Only read when the shader exports e63; the geometry shader is told
        # which by xe_point_size_from_vertex, since a real export can be
        # negative and the hardware clamps that to PA_SU_POINT_MINMAX's min.
        out.append("    float out_point_size = -1.0f;")
        out.append("")

        self._emit_body(out, "    ")

        out.append("")
        if self.projects_position:
            # Before the divide, so it is a narrower frustum rather than a
            # scaled image. See xe_clip_scale.
            out.append("    out_position.xy *= xe_clip_scale;")
        out.append("    output.out_position = out_position;")
        for name in names:
            out.append("    output.out_%s = out_%s;" % (name, name))
        out.append("    output.out_point_size = out_point_size;")
        out.append("    return output;")
        out.append("}")
        return "\n".join(out) + "\n"


class PixelShader(Shader):
    # Only export 0, the single colour target, is used in this title.
    EXPORT_COLOR = 0

    CB_FLOAT = 2
    CB_BOOL = 3

    # The alpha test constants, pixel side only: nothing in a vertex shader can
    # discard. See PRELUDE_ALPHA_TEST.
    CB_ALPHA = 4

    def _scan_fetch(self, address, instr):
        if instr["opcode"] != 1:
            self.unsupported.append(
                "non-texture fetch '%s' at %d" % (instr["name"], address))
            return
        if instr["dimension"] not in (1, 3):
            self.unsupported.append(
                "texture dimension %s at %d"
                % (U.TEX_DIMENSIONS[instr["dimension"]], address))
            return
        if instr["use_reg_lod"] or instr["lod_bias"]:
            self.unsupported.append("explicit LOD at %d" % address)
        if instr["offset_x"] or instr["offset_y"] or instr["offset_z"]:
            self.unsupported.append("texel offset at %d" % address)
        kind = "TextureCube" if instr["dimension"] == 3 else "Texture2D"
        slot = instr["const_index"]
        if self.textures.setdefault(slot, kind) != kind:
            self.unsupported.append(
                "texture slot %d used as both 2D and cube" % slot)
        self.max_temp = max(self.max_temp, instr["dst_reg"], instr["src_reg"])

    def _scan_exports(self):
        if self.EXPORT_COLOR not in self.exports:
            self.unsupported.append("no colour export")
        for export in self.exports:
            if export != self.EXPORT_COLOR:
                self.unsupported.append("unknown export register e%d" % export)

    def _export_target(self, register):
        return "out_color"

    def _emit_fetch(self, instr, out, indent):
        slot = instr["const_index"]
        components = 3 if instr["dimension"] == 3 else 2
        coordinate = "r%d.%s" % (
            instr["src_reg"],
            "".join(COMPONENTS[bits(instr["src_swizzle"], j * 2, 2)]
                    for j in range(components)))
        line = self._fetch_destination(instr, "xe_tf")
        if not line:
            return
        if slot == 13 and components == 2:
            # Refraction uses guest clip coordinates to sample the expanded scene.
            # Every 2D fetch of slot 13 in the pack is this same fetch.
            coordinate = "lerp(float2(0.5f, 0.5f), %s, xe_clip_scale)" % coordinate
        self._emit_block(out, indent, instr, [
            "float4 xe_tf = xe_texture%d.Sample(xe_sampler%d, %s);"
            % (slot, slot, coordinate),
            line,
        ])

    def emit(self, source_name):
        out = self._prelude(source_name)
        state = {"cb_alpha": self.CB_ALPHA, "cb_space": self.CB_SPACE}
        out.append(PRELUDE_ALPHA_TEST % dict(
            state, draw_state=DRAW_STATE_CB % state))

        # Samplers live in their own descriptor set, which is register space 1:
        # Plume maps a descriptor set's index straight onto RegisterSpace. They
        # are split from the textures because a D3D12 shader-visible *sampler*
        # heap holds only 1024 descriptors, so a cache of sets carrying sixteen
        # samplers each runs out after sixty four sets, while the view heap holds
        # 65536. The title binds a few hundred distinct texture combinations and
        # only a handful of distinct sampler ones, so splitting them puts each in
        # a heap it fits in. See AcquireTextureSet in native_renderer_draw.cpp.
        for slot in sorted(self.textures):
            out.append("%s xe_texture%d : register(t%d, space0);"
                       % (self.textures[slot], slot, slot))
            out.append("SamplerState xe_sampler%d : register(s%d, space1);"
                       % (slot, slot))
        if self.textures:
            out.append("")

        out.append("struct PSInput {")
        # Declared, never read. The vertex side's SV_Position takes register 0,
        # so without it here every TEXCOORD would sit one register lower than
        # the one the vertex shader writes it to, and D3D12 matches the two
        # signatures by register. This is the other half of the layout fix
        # described at Shader.interpolator_layout.
        out.append("    float4 in_position : SV_Position;")
        for key in self.layout_keys():
            out.append("    float4 in_p%d : TEXCOORD%d;" % (key, key))
        out.extend(name.replace("out_", "in_")
                   for name in reserved_semantics(self.layout_keys()))
        out.append("};\n")

        out.append("float4 main(PSInput input) : SV_Target0 {")
        self._declare_registers(out)
        out.append("    float4 out_color = 0.0f.xxxx;")
        out.append("")
        # Interpolators arrive in the registers their signature names, which is
        # always the entry's own position in the table.
        for entry in self.interpolators:
            out.append("    r%d = input.in_p%d;"
                       % (entry["register"], entry["key"]))

        # PsParamGen, which the sequencer substitutes for one register rather
        # than the vertex shader exporting it. |zw| is the point sprite
        # coordinate and comes from the geometry shader; xy is the pixel
        # position, whose sign bits encode the facing and the primitive type on
        # the console and are left positive here (nothing in this title reads
        # them). The guest takes abs() of zw itself, per the Xbox 360's
        # SPRITETEXCOORD convention. See PARAM_GEN_KEY.
        #
        # Over every register the shader declares, not just the ones its
        # interpolator signature names: param_gen_pos generally points *past*
        # the signature, because the register is the sequencer's to fill and the
        # shader has nothing to declare for it. ps_014, the flower sprite shader,
        # has two interpolators and reads r2, which is exactly that.
        out.append("")
        out.append("    if (xe_param_gen_enable != 0u) {")
        out.append("        float4 xe_pg = float4(input.in_position.xy,")
        out.append("                              input.in_param_gen.zw);")
        out.append("        switch (xe_param_gen_pos) {")
        for register in range(self.max_temp + 1):
            out.append("            case %du: r%d = xe_pg; break;"
                       % (register, register))
        out.append("            default: break;")
        out.append("        }")
        out.append("    }")
        out.append("")

        self._emit_body(out, "    ")

        out.append("")
        out.append("    xe_alpha_test(out_color.a);")
        out.append("    return out_color;")
        out.append("}")
        return "\n".join(out) + "\n"


def point_sprite_gs(layout, source_name="point_sprite"):
    """Emit the point sprite expansion geometry shader.

    A POINT_LIST draw on the console rasterises each vertex as a screen aligned
    quad sized by the vertex shader's e63 export (or by PA_SU_POINT_SIZE when it
    has none), with the sequencer feeding the pixel shader a [0, 1] coordinate
    across it. A host point list draws one pixel and generates no coordinate, so
    the flower and particle draws in this title produce nothing at all without
    this.

    One shader serves every vertex shader because they all declare the same
    output signature: the interpolator layout is title-wide (see
    Shader.interpolator_layout) and the two varyings this needs are declared
    unconditionally. Everything the guest exported is passed through untouched;
    the only thing this writes is the sprite coordinate.

    Metal has no geometry shaders at all, so the caller has to be prepared for
    this not to be usable; see AcquireGuestPipeline.
    """
    out = ["// Generated by scripts/xenos_hlsl.py -- do not edit.",
           "// Source: %s" % source_name, ""]
    out.append(DRAW_STATE_CB % {"cb_alpha": PixelShader.CB_ALPHA,
                                "cb_space": Shader.CB_SPACE})

    out.append("struct GSVertex {")
    out.append("    float4 out_position : SV_Position;")
    for key in layout:
        out.append("    float4 out_p%d : TEXCOORD%d;" % (key, key))
    out.extend(reserved_semantics(layout))
    out.append("};\n")

    out.append("[maxvertexcount(4)]")
    out.append("void main(point GSVertex input[1], "
               "inout TriangleStream<GSVertex> stream) {")
    out.append("    GSVertex v = input[0];")
    # A NaN position would otherwise expand into a quad covering the target,
    # rather than being dropped the way a degenerate point is.
    out.append("    if (any(isnan(v.out_position))) {")
    out.append("        return;")
    out.append("    }")
    # Rasterisation clamps an e63 diameter to PA_SU_POINT_MINMAX, negatives
    # included (they go to min). Without it this title's petals, which size
    # themselves by 1/w, export diameters in the hundreds of thousands as one
    # crosses the near plane and a single sprite covers the target.
    out.append("    float2 diameter = xe_point_size_from_vertex != 0u")
    out.append("        ? clamp(v.out_point_size.xx, xe_point_size_minmax.x,")
    out.append("                xe_point_size_minmax.y)")
    out.append("        : xe_point_constant_diameter;")
    out.append("    if (diameter.x <= 0.0f || diameter.y <= 0.0f) {")
    out.append("        return;")
    out.append("    }")
    # The position is still pre-divide, so the clip space offset that becomes a
    # fixed number of pixels after the divide scales with w.
    out.append("    float2 radius = diameter * xe_point_screen_to_ndc "
               "* v.out_position.w;")
    out.append("")
    # Triangle strip corners in the order (0,0) (1,0) (0,1) (1,1), which is the
    # order the hardware generates the sprite coordinate in.
    corners =[(0.0, 0.0, -1.0, 1.0), (1.0, 0.0, 1.0, 1.0),
               (0.0, 1.0, -1.0, -1.0), (1.0, 1.0, 1.0, -1.0)]
    for u, t, sx, sy in corners:
        out.append("    v.out_param_gen = float4(0.0f, 0.0f, %.1ff, %.1ff);"
                   % (u, t))
        out.append("    v.out_position.xy = input[0].out_position.xy "
                   "+ float2(%.1ff, %.1ff) * radius;" % (sx, sy))
        out.append("    stream.Append(v);")
    out.append("    stream.RestartStrip();")
    out.append("}")
    return "\n".join(out) + "\n"


def load(directory, name):
    with open(os.path.join(directory, name + ".ucode"), "rb") as handle:
        ucode = handle.read()
    header_path = os.path.join(directory, name + ".header")
    header = None
    if os.path.exists(header_path):
        with open(header_path, "rb") as handle:
            header = handle.read()
    kind = PixelShader if name.startswith("ps_") else VertexShader
    return kind(name, ucode, header)


def translate_all(directory, out_dir, check_only, prefixes=("vs_", "ps_")):
    names = sorted(name[:-len(".ucode")] for name in os.listdir(directory)
                   if name.startswith(prefixes) and name.endswith(".ucode"))
    if out_dir and not check_only:
        os.makedirs(out_dir, exist_ok=True)

    # One interpolator layout across the whole set, for the reason spelled out
    # at Shader.interpolator_layout: a pixel shader has to declare its inputs in
    # the registers the vertex shader it is paired with writes. Costs a second
    # decode of every payload, which only this exploratory path pays.
    layout = set()
    for name in names:
        try:
            layout.update(e["key"] for e in load(directory, name).interpolators)
        except Exception:  # a payload that does not decode is reported below
            pass
    layout = sorted(layout)

    counts = {"vs_": [0, 0, 0], "ps_": [0, 0, 0]}  # translated, skipped, failed
    reasons = {}
    failed = []
    for name in names:
        tally = counts[name[:3]]
        try:
            shader = load(directory, name)
        except Exception as error:  # decode failure, distinct from unsupported
            failed.append("%s: %s" % (name, error))
            tally[2] += 1
            continue
        shader.interpolator_layout = layout
        if shader.unsupported:
            tally[1] += 1
            for reason in shader.unsupported:
                key = reason.split(" at ")[0]
                reasons[key] = reasons.get(key, 0) + 1
            continue
        try:
            text = shader.emit(name)
        except Exception as error:
            failed.append("%s: %s" % (name, error))
            tally[2] += 1
            continue
        tally[0] += 1
        if out_dir and not check_only:
            with open(os.path.join(out_dir, name + ".hlsl"), "w") as handle:
                handle.write(text)

    for prefix, label in (("vs_", "vertex"), ("ps_", "pixel")):
        translated, skipped, errors = counts[prefix]
        if translated + skipped + errors:
            print("%s shaders: %d translated, %d unsupported, %d errors"
                  % (label, translated, skipped, errors))
    for reason, count in sorted(reasons.items(), key=lambda kv: -kv[1]):
        print("    %-48s %d" % (reason, count))
    for message in failed[:20]:
        print("    %s" % message)
    if out_dir and not check_only:
        print("wrote %s" % out_dir)
    return 1 if failed else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", help=".ucode file, or directory with --all")
    parser.add_argument("--all", action="store_true",
                        help="translate every vs_*/ps_*.ucode in the directory")
    parser.add_argument("--vertex", action="store_true",
                        help="with --all, vertex shaders only")
    parser.add_argument("--pixel", action="store_true",
                        help="with --all, pixel shaders only")
    parser.add_argument("-o", "--out-dir", help="with --all, write .hlsl here")
    parser.add_argument("--check", action="store_true",
                        help="with --all, translate but write nothing")
    args = parser.parse_args()

    if args.all:
        prefixes = ("vs_",) if args.vertex else \
                   ("ps_",) if args.pixel else ("vs_", "ps_")
        return translate_all(args.path, args.out_dir, args.check, prefixes)

    directory, filename = os.path.split(os.path.abspath(args.path))
    name = filename[:-len(".ucode")] if filename.endswith(".ucode") else filename
    shader = load(directory, name)
    if shader.unsupported:
        for reason in shader.unsupported:
            print("unsupported: %s" % reason, file=sys.stderr)
        return 1
    sys.stdout.write(shader.emit(name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
